# Generated by Django 6.0.2 on 2026-02-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_student_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulationMatrix',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.course')),
                ('matrix', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSpecificOutcome',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
    ]
