# Generated by Django 5.2.6 on 2026-02-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scheme_course_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImprovementMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_test_name', models.CharField(max_length=100)),
                ('target_assessment_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': 'Student Improvement Mapping',
                'unique_together': {('student', 'course', 'improvement_test_name')},
            },
        ),
    ]
