# Generated by Django 5.2.6 on 2026-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentimprovementmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='improvement_test_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StudentImprovementMap',
        ),
    ]
